#!/bin/sh
#
# The MIT License (MIT)
# Copyright (c) 2026 Naresh Mehta (https://www.naresh.se/)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# SOFTWARE.

# Gatekeeper configuration
# 
# This configuration file defines parameters for the gatekeeper network 
# access control system. Configure these values after installation.
#
# Configuration via UCI commands:
#   uci set gatekeeper.main=gatekeeper
#   uci set gatekeeper.main.token='YOUR_TELEGRAM_BOT_TOKEN_HERE'
#   uci set gatekeeper.main.chat_id='YOUR_CHAT_ID_HERE'
#   uci commit gatekeeper

config gatekeeper 'main'
	# Telegram Bot API Token (required)
	# Obtain from BotFather: https://t.me/botfather
	# Example: option token '1234567890:ABCdefGhIJKlmNoPQRsTUVwxyZ'
	option token 'YOUR_TELEGRAM_BOT_TOKEN_HERE'

	# Telegram Chat ID for notifications (required)
	# Use this command to find your chat ID: https://api.telegram.org/bot<TOKEN>/getUpdates
	# Or send a message to @userinfobot
	# Example: option chat_id '123456789'
	option chat_id 'YOUR_CHAT_ID_HERE'

	# Blacklist Mode (optional, default: 0)
	# 0 = OFF (all devices require approval - normal mode)
	# 1 = ON (only blacklisted MACs require approval, others auto-approved for 24h)
	option blacklist_mode '0'

# Blacklist MAC addresses
# When blacklist mode is ON, only these MACs will require approval
# All other MACs will be auto-approved with 24-hour timeout
# Add MACs via Telegram bot: BL_ADD aa:bb:cc:dd:ee:ff
config blacklist 'blacklist'
	# list mac 'aa:bb:cc:dd:ee:ff'
	# list mac '11:22:33:44:55:66'