#!/bin/sh
#
# The MIT License (MIT)
# Copyright (c) 2026 Naresh Mehta (https://www.naresh.se/)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# SOFTWARE.

# Gatekeeper configuration
# 
# This configuration file defines parameters for the gatekeeper network 
# access control system. Placeholder values are provided below and should be 
# configured during package deployment.

# Telegram Bot API Token (required)
# Obtain from BotFather: https://t.me/botfather
# Example: TOKEN="1234567890:ABCdefGhIJKlmNoPQRsTUVwxyZ"
option token "YOUR_TELEGRAM_BOT_TOKEN_HERE"

# Telegram Chat ID for notifications (required)  
# Use this command to find your chat ID: https://api.telegram.org/bot<TOKEN>/getUpdates
# Or send a message to @userinfobot
# Example: CHAT_ID="123456789"
option chat_id "YOUR_CHAT_ID_HERE"