#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95 # Starts late in the boot process

start_service() {
    procd_open_instance "gatekeeper_trigger_listener"
    # Points to the listener script we created in the previous step
    procd_set_param command /bin/sh /usr/bin/gatekeeper_trigger.sh
    procd_set_param respawn # Automatically restart if it fails
    procd_set_param stdout 1 # Log output to logread
    procd_set_param stderr 1
    procd_close_instance
}

# Enable using below commands.
# chmod +x /etc/init.d/gatekeeper_trigger_listener
# /etc/init.d/gatekeeper_trigger_listener enable
# /etc/init.d/gatekeeper_trigger_listener start
